### ISSUE TITLE
[forge-autocomplete] autocompletes used in dialogs can cause browser to jump to top of page after second selection

### ISSUE THREAD

**Issue by cstaib1** [tyler-technologies-oss/forge#377] opened 2023-09-15 16:45 UTC
**Describe the bug:**
When opening a forge-dialog at the bottom of a vertically scrollable page, if I click an autocomplete with multiple enabled to select options then click away from the autocomplete and click it to select more options, the page in the background of the dialog will jump to the top. I've only been able to replicate this on autocompletes with a lot of options, in our case, ~400+. 

**To Reproduce:**
1. Create a simple page with enough height to scroll.
2. Scroll to the bottom of the page.
3. Prompt a forge-dialog that contains a multiple select autocomplete with at least 400 options.
4. Click 1-2 options in the autocomplete dropdown to select them.
5. Click away from the autocomplete, but still on the dialog. (Click other components will also work here as long as they are on the dialog)
6. Click the autocomplete to prompt the dropdown options to display.
7. Notice the page (behind the dialog) has now jumped to the top.  

**Expected behavior:**
The popup menu generated by autocompletes should not cause the background page to move when selecting options on an autocomplete or any other component nested within.

**Screenshots:**
N/A

**Please complete the following information:**
 - Forge version: 2.16.3 (Tested with 2.16.6 and still present)
 - I have searched existing issues before creating this report? Y
 - Browser: Chrome
 - Platform: Desktop
 - OS: Windows

**Additional context:**
I mentioned this as an issue last year around October on call with Kieran, but had not made an issue on github to report it. It was explained to be a bug when we talked about it and appeared to come from the popup menu for autocompletes first rendering to the top left of pages then transforming to the location of the autocomplete element. If more additional context is needed, feel free to contact me on Teams and I can provide a live demo of the issue.

**Comment by DRiFTy17** [comment] 2023-09-27 16:37
I spent a bit today trying to replicate this issue, but I didn't have any luck...

Could you create a reproduction in StackBlitz potentially? Otherwise, we could hop on a call and screen share to debug on your machine as well.

**Comment by DRiFTy17** [comment] 2024-06-14 14:20
This won't occur in 3.0 implementation due to rest of page being inert. Closing, but feel free to reopen if you find it to still be an issue.

**Closed by DRiFTy17** 2024-06-14 14:20 UTC
Labels: bug
